name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Install CFITSIO (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libcfitsio-dev

      - name: Install CFITSIO (macOS)
        if: runner.os == 'macOS'
        run: brew install cfitsio

      - name: Install vcpkg and CFITSIO (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install cfitsio:x64-windows

      - name: Set up vcpkg env (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "LIB=$(pwd)\vcpkg\installed\x64-windows\lib" >> $env:GITHUB_ENV
          echo "PATH=$(pwd)\vcpkg\installed\x64-windows\bin;$env:PATH" >> $env:GITHUB_ENV

      - name: Build and test
        run: dub test
